//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_albums_member_id_name")]
    pub member_id: i64,
    #[sea_orm(unique_key = "idx_albums_member_id_name")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub cover_file_id: Option<i64>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(has_many)]
    pub album_files: HasMany<super::album_files::Entity>,
    #[sea_orm(
        belongs_to,
        from = "member_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub members: HasOne<super::members::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
