//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "album_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "idx_album_files_album_id_member_file_id")]
    pub album_id: i64,
    #[sea_orm(unique_key = "idx_album_files_album_id_member_file_id")]
    pub member_file_id: i64,
    pub created_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "album_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub albums: HasOne<super::albums::Entity>,
    #[sea_orm(
        belongs_to,
        from = "member_file_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub member_files: HasOne<super::member_files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
