//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "file_contents")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub content_hash: String,
    pub file_size: i64,
    pub storage_path: String,
    pub mime_type: String,
    pub width: i64,
    pub height: i64,
    pub duration: i64,
    pub ref_count: i64,
    pub created_at: DateTimeUtc,
    pub first_uploaded_by: i64,
    #[sea_orm(has_many)]
    pub member_files: HasMany<super::member_files::Entity>,
    #[sea_orm(
        belongs_to,
        from = "first_uploaded_by",
        to = "id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    pub members: HasOne<super::members::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
