//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// Member role enum
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(20))")]
pub enum MemberRole {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "user")]
    User,
}

impl Default for MemberRole {
    fn default() -> Self {
        Self::User
    }
}

impl MemberRole {
    pub fn is_admin(&self) -> bool {
        matches!(self, Self::Admin)
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub username: String,
    pub password: String,
    pub avatar: Option<String>,
    #[sea_orm(unique)]
    pub storage_tag: String,
    pub created_at: DateTimeUtc,
    pub role: MemberRole,
    #[sea_orm(has_many)]
    pub file_contents: HasMany<super::file_contents::Entity>,
    #[sea_orm(has_many)]
    pub member_files: HasMany<super::member_files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
