//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "member_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub member_id: i64,
    pub file_content_id: i64,
    pub file_name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    #[sea_orm(
        belongs_to,
        from = "file_content_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    pub file_contents: HasOne<super::file_contents::Entity>,
    #[sea_orm(
        belongs_to,
        from = "member_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    pub members: HasOne<super::members::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
