//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "members")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub username: String,
    pub password: String,
    pub avatar: Option<String>,
    #[sea_orm(unique)]
    pub storage_tag: String,
    pub created_at: DateTimeUtc,
    #[sea_orm(has_many)]
    pub file_contents: HasMany<super::file_contents::Entity>,
    #[sea_orm(has_many)]
    pub member_files: HasMany<super::member_files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
