//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sync_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub message_type: String, // sync_directory, sync_database
    pub progress: i32,        // 0-100
    pub status: String,       // pending, processing, completed, failed
    #[sea_orm(column_type = "Text")]
    pub payload: String, // JSON payload
    #[sea_orm(column_type = "Text")]
    pub error_message: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub completed_at: Option<DateTimeUtc>,
}

impl ActiveModelBehavior for ActiveModel {}

/// Enum for sync message types
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SyncMessageType {
    SyncDirectory, // 从目录同步到数据库
    SyncDatabase,  // 从数据库同步到目录
}

impl SyncMessageType {
    pub fn as_str(&self) -> &'static str {
        match self {
            SyncMessageType::SyncDirectory => "sync_directory",
            SyncMessageType::SyncDatabase => "sync_database",
        }
    }
}

impl TryFrom<String> for SyncMessageType {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "sync_directory" => Ok(SyncMessageType::SyncDirectory),
            "sync_database" => Ok(SyncMessageType::SyncDatabase),
            _ => Err(format!("Unknown sync message type: {}", value)),
        }
    }
}

/// Enum for sync status
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SyncStatus {
    Pending,    // 等待处理
    Processing, // 处理中
    Completed,  // 完成
    Failed,     // 失败
}

impl SyncStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            SyncStatus::Pending => "pending",
            SyncStatus::Processing => "processing",
            SyncStatus::Completed => "completed",
            SyncStatus::Failed => "failed",
        }
    }
}

impl TryFrom<String> for SyncStatus {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "pending" => Ok(SyncStatus::Pending),
            "processing" => Ok(SyncStatus::Processing),
            "completed" => Ok(SyncStatus::Completed),
            "failed" => Ok(SyncStatus::Failed),
            _ => Err(format!("Unknown sync status: {}", value)),
        }
    }
}
