//! `SeaORM` Entity, @generated by sea-orm-codegen

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "task_messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub member_id: i64,
    pub message_type: String,
    pub progress: i32,  // 0-100
    pub status: String, // pending, processing, completed, failed
    #[sea_orm(column_type = "Text")]
    pub payload: String, // JSON payload
    #[sea_orm(column_type = "Text")]
    pub error_message: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub completed_at: Option<DateTimeUtc>,
}

impl ActiveModelBehavior for ActiveModel {}

/// Enum for task status
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskStatus {
    Pending,    // 等待处理
    Processing, // 处理中
    Completed,  // 完成
    Failed,     // 失败
}

impl TaskStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            TaskStatus::Pending => "pending",
            TaskStatus::Processing => "processing",
            TaskStatus::Completed => "completed",
            TaskStatus::Failed => "failed",
        }
    }
}

impl TryFrom<String> for TaskStatus {
    type Error = String;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        match value.as_str() {
            "pending" => Ok(TaskStatus::Pending),
            "processing" => Ok(TaskStatus::Processing),
            "completed" => Ok(TaskStatus::Completed),
            "failed" => Ok(TaskStatus::Failed),
            _ => Err(format!("Unknown task status: {}", value)),
        }
    }
}
